### ISSUE TITLE
Calendar "jumps" on select if multiple months are displayed

### ISSUE THREAD

**Issue by anush** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#16]
If the `numberOfMonths` value is set to greater than 1, anytime you select a date in a month other than the first month, the calendar moves the month that you just selected to become the first month, causing a "jump".

For example, I've set `numberOfMonths = 2` and the calendar currently displays Jan and Feb. If I pick a date in Jan, there is no problem. But if I pick a date in Feb, the calendar refreshes and now displays Feb and Mar. 

It may have something to do with the `showCurrentAtPos` option, but the issue only seems to happen with MDP and not with the standard datepicker.

**Comment by attam333** [comment]
I've a problem about multiDatesPicker...
var today = new Date();
	var y = today.getFullYear();
	$('#custom-date-format').multiDatesPicker({
		addDates: ['01/14/'+y, '01/19/'+y, '01/14/'+y, '02/16/'+y],
		numberOfMonths: [1,1],
		defaultDate: '1/1/'+y
	});
This sets the Date of January month and feb 16 date but calander show the 4 Aug of 2020 year...

**Comment by gavinlaw** [comment]
Below option resolved jumping issue when multiple dates selected across different months

var tempSelectedDate = '';
	
beforeShow: function(input, inst) {
	inst.settings.defaultDate = tempSelectedDate;
},
onSelect: function(date) {
	tempSelectedDate = date;
}

**Comment by michaelc4** [comment]
My solution is:

                // generates the new string of added dates
                var inputs_values = $this.multiDatesPicker('value');

                // fills the input field back with all the dates in the calendar
                if (this.tagName == 'INPUT') $this.val(inputs_values);

                // Fixes the altField filled with defaultDate by default
                var altFieldOption = $this.datepicker('option', 'altField');
                if (altFieldOption) $(altFieldOption).val(inputs_values);

                // Updates the calendar view
                //$this.datepicker('refresh'); <------------- line 177

Because this line makes the code run two times.

1st Refresh when create a element
![image](https://cloud.githubusercontent.com/assets/16707218/12332210/5c6cb13c-bad4-11e5-8255-afa0408cf1a0.png)
result jquery ui
![image](https://cloud.githubusercontent.com/assets/16707218/12332273/a856c02e-bad4-11e5-9376-ea16ee69dd7f.png)


2nd refresh in sequence inside multipledatespicker
![image](https://cloud.githubusercontent.com/assets/16707218/12332304/daa7def0-bad4-11e5-9348-dd00de49eff8.png)
result jquery ui
![image](https://cloud.githubusercontent.com/assets/16707218/12332343/0bae1ca8-bad5-11e5-88b1-c3ce03f5dfa6.png)

this makes two moves 1st:(January ->December) 2nd(December->November)

**Comment by dubrox** [comment]
Here a demostration of the effects of the option `showCurrentAtPos` on multiple months calendar, both with vanilla jQuery UI datepicker and MDP: http://jsfiddle.net/y0oLyyxu/2/
As you can see, it is not an MDP issue. 

I'll test if removing the refresh mentioned by  @michaelc4 suggests doesn't break the funcionality, so to avoid unneeded code execution. What I know is that it doesn't solve the jumping problem (already tested).
